/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import acceso_a_datos.conexion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica_de_negocios.venta;
import logica_de_negocios.ventas;

/**
 *
 * @author Vanessa
 */
import javax.swing.table.DefaultTableModel;
import logica_de_negocios.cliente;
import logica_de_negocios.clientes;
import logica_de_negocios.producto;
public class FacturasEmitidas extends javax.swing.JFrame {

    /**
     * Creates new form FacturasEmitidas
     */
    conexion c;
    ventas vts;
    ArrayList<venta> ventas;
    DefaultTableModel tabla;
    DefaultTableModel tabla2;
    venta v;
    double ingreso;
    public FacturasEmitidas(conexion c) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.ingreso = 0.0;
        this.c = c;
        this.v = new venta();
        this.vts = new ventas();
        this.tabla = (DefaultTableModel) jTable1.getModel();
         this.tabla2 = (DefaultTableModel) jTable2.getModel();
        ventas = vts.getventas(this.c.getConexion(), this.c.getEstado());
         if(this.ventas.size() == 0)
        {
            JOptionPane.showMessageDialog(this,"No hay ventas");
        }
        else
        {
           v = ventas.get(0);
           for(producto p:v.getcanasta())
           {
               tabla.addRow(new Object[]{p.getnombre(),p.getprec_uni(),p.getcantidad(),p.getprec_uni()*p.getcantidad()});
           }     
           lblid.setText(v.getid() + "");
           lbltotal.setText(v.getpreciototal() + "");
           labelcliente.setText(v.getcliente().getnombre());
           labelempleado.setText(v.getempleado().getnombre());
           labelfecha.setText(v.getfecha());
        }
         llenartabla();
         obteneringreso();
        lblingreso.setText(this.ingreso +"");
    }
    
    public void obteneringreso()
    {
        int filas=tabla2.getRowCount();
            for (int i = 0;filas>i; i++) {
                this.ingreso += Double.parseDouble(tabla2.getValueAt(i,2).toString());
            }
    }
    public void llenartabla()
    {
        //limpiar tabla
        int filas=tabla2.getRowCount();
            for (int i = 0;filas>i; i++) {
                tabla2.removeRow(0);
            }
            //llenado de tabla
        for(venta v:this.ventas)
           {
               tabla2.addRow(new Object[]{v.getcliente().getnombre(),v.getempleado().getnombre(),v.getpreciototal()});
           }  
    }
    
    public void llenar()
    {
        int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                tabla.removeRow(0);
            }
         for(producto p:v.getcanasta())
           {
               tabla.addRow(new Object[]{p.getnombre(),p.getprec_uni(),p.getcantidad(),p.getprec_uni()*p.getcantidad()});
           }     
           lblid.setText(v.getid() + "");
           lbltotal.setText(v.getpreciototal() + "");
           labelcliente.setText(v.getcliente().getnombre());
           labelempleado.setText(v.getempleado().getnombre());
           labelfecha.setText(v.getfecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelcliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelfecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelempleado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtbnombrecliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtbnombreempleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblingreso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 24)); // NOI18N
        jLabel1.setText("LIBRERIA SILUETA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Santa Ana");

        jLabel3.setText("Tel: 2415-1407");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio Unidad", "Cantidad", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Total:");

        lbltotal.setText("00");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("ID FACTURA:");

        lblid.setText("0");

        jLabel5.setText("CLIENTE:");

        labelcliente.setText("NOMBRE  .");

        jLabel8.setText("FECHA:");

        labelfecha.setText("XX/XX/XX");

        jLabel7.setText("EMPLEADO:");

        labelempleado.setText("NOMBRE DEL EMPLEADO");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Cliente", "Nombre Vendedor", "Total de Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel9.setText("Nombre de cliente");

        txtbnombrecliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbnombreclienteKeyReleased(evt);
            }
        });

        jLabel10.setText("Nombre de vendedor");

        txtbnombreempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbnombreempleadoActionPerformed(evt);
            }
        });
        txtbnombreempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbnombreempleadoKeyReleased(evt);
            }
        });

        jLabel11.setText("Ganancias Totales: $");

        lblingreso.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(404, 404, 404)
                                .addComponent(jButton2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelcliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelempleado)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(labelfecha))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbltotal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel9))
                                    .addComponent(txtbnombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel10)))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblingreso)
                                .addGap(2, 2, 2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblid)
                            .addComponent(jLabel5)
                            .addComponent(labelcliente)
                            .addComponent(jLabel8)
                            .addComponent(labelfecha)
                            .addComponent(jLabel7)
                            .addComponent(labelempleado))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbltotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(txtbnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbnombreempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblingreso))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(v.getid() == ventas.get(0).getid())
        {
            JOptionPane.showMessageDialog(this,"ya esta al principio");
        }
        else
        {
            int index = 0;
            for(venta vv:ventas)
            {
                if(vv.getid() == v.getid())
                {
                    break;
                }
                index += 1;
            }
            v = ventas.get(index - 1);
            llenar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(ventas.get(this.ventas.size()-1).getid() == v.getid())
        {
            JOptionPane.showMessageDialog(this,"ya esta al final");
        }
        else
        {
            int index = 0;
            for(venta vv:ventas)
            {
                if(v.getid() == vv.getid())
                {
                    break;
                }
                index += 1;
            }
            v = ventas.get(index + 1);
            llenar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtbnombreempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbnombreempleadoActionPerformed
       
    }//GEN-LAST:event_txtbnombreempleadoActionPerformed

    private void txtbnombreclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbnombreclienteKeyReleased
        String letra = "";
        letra = txtbnombrecliente.getText();
        if(letra.equals(""))
        {
           // this.clients.clear();
            this.ventas = this.vts.getventas(this.c.getConexion(), this.c.getEstado());
            this.llenar();
            this.llenartabla();
        }
        else
        {    
           //this.clients.clear();
           this.ventas = this.vts.getventaletracliente(letra, this.c.getConexion(), this.c.getEstado());
           this.llenartabla();
           this.v = this.ventas.get(0);
           this.llenar();
           llenartabla();
        } 
    }//GEN-LAST:event_txtbnombreclienteKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        clientes clits = new clientes();
        String nombre = tabla2.getValueAt(jTable2.getSelectedRow(), 0).toString();
        cliente cl = clits.getclientebyname(nombre, this.c.getConexion(), this.c.getEstado());
        this.v = this.vts.getventabyidcliente(cl.getid(), this.c.getConexion(), this.c.getEstado());
        this.llenar();
        this.llenartabla();
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtbnombreempleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbnombreempleadoKeyReleased
        String letra = "";
        letra = txtbnombreempleado.getText();
        if(letra.equals(""))
        {
           // this.clients.clear();
            this.ventas = this.vts.getventas(this.c.getConexion(), this.c.getEstado());
            this.llenar();
            this.llenartabla();
        }
        else
        {    
           //this.clients.clear();
           this.ventas = this.vts.getventaletraempleado(letra, this.c.getConexion(), this.c.getEstado());
           this.llenartabla();
           this.v = this.ventas.get(0);
           this.llenar();
           llenartabla();
        } 
    }//GEN-LAST:event_txtbnombreempleadoKeyReleased

    /**
     * @param args the command line arguments
     */
    public void main() {
                new FacturasEmitidas(this.c).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelcliente;
    private javax.swing.JLabel labelempleado;
    private javax.swing.JLabel labelfecha;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblingreso;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTextField txtbnombrecliente;
    private javax.swing.JTextField txtbnombreempleado;
    // End of variables declaration//GEN-END:variables
}
